### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by asif-mahmud** [jmercouris/emacs-centered-point#1]
I just wanted to say, thanks a lot. I was looking at some other options and all of them did more than i asked for. I just wanted the cursor to stay at middle, this little code does that beautifully. Please consider to put it on MELPA or ELPA.

**Comment by jmercouris** [comment]
I may consider, it, thank you for your kind comment :-)

**Comment by asif-mahmud** [comment]
hi, i have been using your code snippet directly, it was working perfectly until i tried to use magit. Magit fails to open commit message buffer with this mode on. Fortunately, i opened an issue in magit repo, one of them suggested the following change in this code and now its working fine with magit.

```
(defun line-change ()
  (when (eq (get-buffer-window)
            (selected-window) )
    (recenter)))
```

**Comment by asif-mahmud** [comment]
i have opened a pr to use this code #2
